services:
  database:
    image: postgres:17-alpine
    container_name: forgefit-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: forgefit
      POSTGRES_PASSWORD: forgefit_password
      POSTGRES_DB: forgefit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forgefit-network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: forgefit-redis
    ports:
      - "6379:6379"
    networks:
      - forgefit-network
    restart: always

networks:
  forgefit-network:
    driver: bridge

volumes:
  postgres_data:
