FROM node:22-alpine AS builder

RUN npm install -g pnpm@10.8.1

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

COPY tooling ./tooling
COPY apps/api ./apps/api

RUN pnpm install --frozen-lockfile

RUN pnpm --filter api build

FROM node:22-alpine AS runner
WORKDIR /app/apps/api

ENV NODE_ENV=production

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/apps/api/node_modules ./node_modules
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/apps/api/package.json ./package.json
COPY --from=builder /app/apps/api/scripts/register-paths.js ./scripts/register-paths.js

EXPOSE 3000

CMD ["npm", "start"]
